benchmarking:
  random_seed: 42

  common_datasets:
    gradient_boosting:
      sample_generator: sklearn.datasets.make_classification
      params:
        n_classes: 5
        n_informative: 5
        n_redundant: 0
      n_features: 1e2
      n_samples_train:
        - 1e5
      n_samples_test:
        - 1e3

  estimators:
    KNeighborsClassifier_brute_force:
      name: KNeighborsClassifier_brute_force
      estimator: sklearn.neighbors.KNeighborsClassifier
      benchmarking_method: hp_match
      predict_with_onnx: True
      parameters:
        init:
          n_neighbors:
            - 1
            - 5
            - 100
          algorithm:
            - brute
          n_jobs:
            - -1
            - 1
      metrics:
        - accuracy_score
      datasets:
        - sample_generator: sklearn.datasets.make_classification
          params:
            n_classes: 2
            n_redundant: 0
          n_features: 1e2
          n_samples_train:
            - 1e5
          n_samples_test:
            - 1
            - 1e3
        - sample_generator: sklearn.datasets.make_classification
          params:
            n_classes: 2
            n_redundant: 0
          n_features: 2
          n_samples_train:
            - 1e5
          n_samples_test:
            - 1
            - 1e3

    sklearnex_KNeighborsClassifier_brute_force:
      inherit: KNeighborsClassifier_brute_force
      estimator: sklearnex.neighbors.KNeighborsClassifier

    KNeighborsClassifier_kd_tree:
      name: KNeighborsClassifier_kd_tree
      estimator: sklearn.neighbors.KNeighborsClassifier
      benchmarking_method: hp_match
      predict_with_onnx: True
      parameters:
        init:
          n_neighbors:
            - 1
            - 5
            - 100
          algorithm:
            - kd_tree
          n_jobs:
            - -1
            - 1
      metrics:
        - accuracy_score
      datasets:
        - sample_generator: sklearn.datasets.make_classification
          params:
            n_classes: 2
            n_redundant: 0
          n_features: 10
          n_samples_train:
            - 1e6
          n_samples_test:
            - 1
            - 1e3
        - sample_generator: sklearn.datasets.make_classification
          params:
            n_classes: 2
            n_redundant: 0
          n_features: 2
          n_samples_train:
            - 1e3
          n_samples_test:
            - 1
            - 1e3

    sklearnex_KNeighborsClassifier_kd_tree:
      inherit: KNeighborsClassifier_kd_tree
      estimator: sklearnex.neighbors.KNeighborsClassifier

    KMeans_tall:
      name: KMeans_tall
      estimator: sklearn.cluster.KMeans
      benchmarking_method: hp_match
      parameters:
        init:
          init:
            - k-means++
            - random
          algorithm:
            - full
          n_clusters:
            - 3
          max_iter:
            - 30
          n_init:
            - 1
          tol:
            - 1e-16
      metrics:
        - adjusted_rand_score
      datasets:
        - sample_generator: sklearn.datasets.make_blobs
          params:
            cluster_std: 20.0
            centers: 200
          n_features: 2
          n_samples_train:
            - 1e6
          n_samples_test:
            - 1
            - 1e3
        - sample_generator: sklearn.datasets.make_blobs
          params:
            cluster_std: 20.0
            centers: 200
          n_features: 1e2
          n_samples_train:
            - 1e6
          n_samples_test:
            - 1
            - 1e3

    sklearnex_KMeans_tall:
      inherit: KMeans_tall
      estimator: sklearnex.cluster.KMeans

    KMeans_short:
      name: KMeans_short
      estimator: sklearn.cluster.KMeans
      benchmarking_method: hp_match
      parameters:
        init:
          init:
            - k-means++
            - random
          algorithm:
            - full
          n_clusters:
            - 300
          max_iter:
            - 20
          n_init:
            - 1
          tol:
            - 1e-16
      metrics:
        - adjusted_rand_score
      datasets:
        - sample_generator: sklearn.datasets.make_blobs
          params:
            cluster_std: 20.0
            centers: 200
          n_features: 2
          n_samples_train:
            - 1e4
          n_samples_test:
            - 1
            - 1e3
        - sample_generator: sklearn.datasets.make_blobs
          params:
            cluster_std: 13.0
            centers: 200
          n_features: 1e2
          n_samples_train:
            - 1e4
          n_samples_test:
            - 1
            - 1e3

    sklearnex_KMeans_short:
      inherit: KMeans_short
      estimator: sklearnex.cluster.KMeans

    LogisticRegression:
      name: LogisticRegression
      estimator: sklearn.linear_model.LogisticRegression
      benchmarking_method: hp_match
      metrics:
        - accuracy_score
      datasets:
        - sample_generator: sklearn.datasets.make_classification
          params:
            n_classes: 5
            n_informative: 5
            n_redundant: 0
          n_features: 1e2
          n_samples_train:
            - 1e6
          n_samples_test:
            - 1
            - 1e3
        - sample_generator: sklearn.datasets.make_classification
          params:
            n_classes: 5
            n_informative: 5
            n_redundant: 0
          n_features: 1e4
          n_samples_train:
            - 1e3
          n_samples_test:
            - 1
            - 1e2

    sklearnex_LogisticRegression:
      inherit: LogisticRegression
      estimator: sklearnex.linear_model.LogisticRegression

    Ridge:
      name: Ridge
      estimator: sklearn.linear_model.Ridge
      benchmarking_method: hp_match
      metrics:
        - r2_score
      datasets:
        - sample_generator: sklearn.datasets.make_regression
          params:
            n_informative: 10
          n_features: 1e4
          n_samples_train:
            - 1e3
          n_samples_test:
            - 1
            - 1e3
        - sample_generator: sklearn.datasets.make_regression
          params:
            n_informative: 10
          n_features: 1e2
          n_samples_train:
            - 1e6
          n_samples_test:
            - 1
            - 1e3

    sklearnex_Ridge:
      inherit: Ridge
      estimator: sklearnex.linear_model.Ridge

    HistGradientBoostingClassifier_best:
      name: HistGradientBoostingClassifier_best
      estimator: sklearn.ensemble.HistGradientBoostingClassifier
      predict_with_onnx: True
      benchmarking_method: hp_match
      metrics:
        - accuracy_score
      parameters:
        init:
          learning_rate:
            - 0.01
          n_iter_no_change:
            - 10
          max_leaf_nodes:
            - 100
          max_bins:
            - 255
          min_samples_leaf:
            - 100
          max_iter:
            - 300
      datasets:
        - sample_generator: sklearn.datasets.make_classification
          params:
            n_classes: 5
            n_informative: 5
            n_redundant: 0
          n_features: 1e2
          n_samples_train:
            - 1e5
          n_samples_test:
            - 1
            - 1e3

    HistGradientBoostingClassifier:
      name: HistGradientBoostingClassifier
      estimator: sklearn.ensemble.HistGradientBoostingClassifier
      predict_with_onnx: True
      benchmarking_method: hpo
      time_budget: 600
      metrics:
        - accuracy_score
      parameters:
        init:
          learning_rate:
            - 0.01
            - 0.05
            - 0.1
            - 0.5
            - 1.
          n_iter_no_change:
            - 10
          max_leaf_nodes:
            - 3
            - 10
            - 30
            - 100
          max_bins:
            - 32
            - 64
            - 128
            - 255
          min_samples_leaf:
            - 2
            - 10
            - 20
            - 100
            - 200
          max_iter:
            - 10
            - 30
            - 100
            - 300
          early_stopping:
            - False
      datasets:
        - name: gradient_boosting

    lightgbm:
      name: LGBMClassifier
      estimator: lightgbm.LGBMClassifier
      benchmarking_method: hpo
      time_budget: 600
      metrics:
        - accuracy_score
      parameters:
        init:
          learning_rate:
            - 0.01
            - 0.05
            - 0.1
            - 0.5
            - 1.
          num_leaves:
            - 3
            - 10
            - 30
            - 100
          max_bin:
            - 32
            - 64
            - 128
            - 255
          min_data_in_leaf:
            - 2
            - 10
            - 20
            - 100
            - 200
          bagging_fraction:
            - 0.5
            - 0.8
            - 1
          feature_fraction_bynode:
            - 0.5
            - 0.8
            - 1
          n_estimators:
            - 10
            - 30
            - 100
            - 300
      datasets:
        - name: gradient_boosting

    xgboost:
      name: XGBClassifier
      estimator: xgboost.XGBClassifier
      benchmarking_method: hpo
      time_budget: 600
      metrics:
        - accuracy_score
      parameters:
        init:
          validate_parameters:
            - True
          tree_method:
            - hist
          use_label_encoder:
            - False
          learning_rate:
            - 0.01
            - 0.05
            - 0.1
            - 0.5
            - 1.
          max_leaves:
            - 3
            - 10
            - 30
            - 100
          max_bin:
            - 32
            - 64
            - 128
            - 255
          min_child_weight:
            - 2
            - 10
            - 20
            - 100
            - 200
          subsample:
            - 0.5
            - 0.8
            - 1
          colsample_bynode:
            - 0.5
            - 0.8
            - 1
          n_estimators:
            - 10
            - 30
            - 100
            - 300
      datasets:
        - name: gradient_boosting

    catboost_lossguide:
      name: CatBoostClassifier_lossguide
      estimator: catboost.CatBoostClassifier
      benchmarking_method: hpo
      time_budget: 600
      metrics:
        - accuracy_score
      parameters:
        init:
          allow_writing_files:
            - False
          grow_policy:
            - Lossguide
          bootstrap_type:
            - MVS
          learning_rate:
            - 0.01
            - 0.05
            - 0.1
            - 0.5
            - 1.
          max_leaves:
            - 3
            - 10
            - 30
            - 100
          border_count:
            - 32
            - 64
            - 128
            - 255
          min_data_in_leaf:
            - 2
            - 10
            - 20
            - 100
            - 200
          subsample:
            - 0.5
            - 0.8
            - 1
          rsm:
            - 0.5
            - 0.8
            - 1
          max_depth:
            - 4
            - 5
            - 6
            - 7
            - 8
            - 9
            - 10
          iterations:
            - 10
            - 30
            - 100
            - 300
      datasets:
        - name: gradient_boosting

    catboost_symmetric:
      name: CatBoostClassifier_symmetric
      estimator: catboost.CatBoostClassifier
      benchmarking_method: hpo
      time_budget: 600
      metrics:
        - accuracy_score
      parameters:
        init:
          allow_writing_files:
            - False
          grow_policy:
            - SymmetricTree
          bootstrap_type:
            - MVS
          learning_rate:
            - 0.01
            - 0.05
            - 0.1
            - 0.5
            - 1.
          border_count:
            - 32
            - 64
            - 128
            - 255
          min_data_in_leaf:
            - 2
            - 10
            - 20
            - 100
            - 200
          subsample:
            - 0.5
            - 0.8
            - 1
          rsm:
            - 0.5
            - 0.8
            - 1
          max_depth:
            - 4
            - 5
            - 6
            - 7
            - 8
            - 9
            - 10
          iterations:
            - 10
            - 30
            - 100
            - 300
      datasets:
        - name: gradient_boosting

hp_match_reporting:
  sklearnex:
    n_cols: 2
    estimators:
      KNeighborsClassifier_brute_force:
        name: KNeighborsClassifier_brute_force
        other_library: sklearnex
        split_bars_by_parameters:
          - n_jobs

      KNeighborsClassifier_kd_tree:
        name: KNeighborsClassifier_kd_tree
        other_library: sklearnex
        split_bars_by_parameters:
          - n_jobs

      KMeans_tall:
        name: KMeans_tall
        other_library: sklearnex

      KMeans_short:
        name: KMeans_short
        other_library: sklearnex

      LogisticRegression:
        name: LogisticRegression
        other_library: sklearnex

      Ridge:
        name: Ridge
        other_library: sklearnex

  onnx:
    n_cols: 2
    relevant_functions:
      - predict
    estimators:
      KNeighborsClassifier_brute_force:
        name: KNeighborsClassifier_brute_force
        other_library: onnx
        split_bars_by_parameters:
          - n_jobs

      KNeighborsClassifier_kd_tree:
        name: KNeighborsClassifier_kd_tree
        other_library: onnx
        split_bars_by_parameters:
          - n_jobs

      HistGradientBoostingClassifier_best:
        name: HistGradientBoostingClassifier_best
        other_library: onnx

hpo_reporting:
  speedup_thresholds:
    - 0.735
    - 0.77
    - 0.805
  estimators:
    HistGradientBoostingClassifier:
      lib: sklearn
      legend: scikit-learn
      color: blue

    LGBMClassifier:
      lib: lightgbm
      color: red

    XGBClassifier:
      lib: xgboost
      color: green

    CatBoostClassifier_lossguide:
      lib: catboost
      legend: catboost lossguide
      color: purple

    CatBoostClassifier_symmetric:
      lib: catboost
      legend: catboost symmetric
      color: orange
